version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
    volumes:
      - ./database/entrypoint:/docker-entrypoint-initdb.d/
      - ./database/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always